spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms36?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Aditya@123
    driver-class-name: com.mysql.cj.jdbc.Driver   # ðŸ‘ˆ add this

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect   # ðŸ‘ˆ recommended

  application:
    name: 12-IRCTCAPP-RestApiDevelopment


