apiVersion: apps/v1
kind: Deployment
metadata:
  name: irctc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irctc
  template:
    metadata:
      labels:
        app: irctc
    spec:
      containers:
        - name: irctc
          image: adityag14/irctc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/irctcdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: irctc-svc
spec:
  selector:
    app: irctc
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
