
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: irctc-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - webapps
  selector:
    matchLabels:
      app: irctc
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
